k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_tdshop-sandbox-ops_asia-southeast1-a_gke-ops-sg
  currentCluster: gke_tdshop-sandbox-ops_asia-southeast1-a_gke-ops-sg
  clusters:
    gke_tdshop-nonprod_asia-southeast1-a_tdshop-nonprod-airflow:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_tdshop-nonprod_asia-southeast1_tdshop-nonprod-backend:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_tdshop-nonprod_asia-southeast1_tdshop-nonprod-chaos:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_tdshop-nonprod_asia-southeast1_tdshop-nonprod-devops:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_tdshop-sandbox-ops_asia-southeast1-a_gke-ops-sg:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_tdshop-shared-service-nonprod_asia-southeast1_gke-nonprod-observability:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    minikube:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-kai
